BEGIN;

TRUNCATE inventory.item CASCADE;
ALTER SEQUENCE inventory.item_item_id_seq RESTART;

-- TABLES
\i schemas/inventory/tables/item_price.sql
\i schemas/inventory/tables/item_quantity.sql
\i schemas/inventory/tables/item_type.sql
\i schemas/inventory/tables/item_file_path_orgin.sql
\i schemas/inventory/tables/item_file_path.sql
\i schemas/inventory/tables/item.sql
\i schemas/inventory/tables/sale_item.sql
\i schemas/inventory/tables/sale_item_item.sql
\i schemas/inventory/tables/sale_group.sql
\i schemas/inventory/tables/sale_group_sale_item.sql
\i schemas/transaction/tables/sale_item_ordered.sql
\i schemas/transaction/tables/order_shipping.sql
\i schemas/transaction/tables/order_billing.sql
\i schemas/users/tables/user.sql
\i schemas/transaction/tables/order.sql
\i schemas/transaction/tables/address.sql
\i schemas/inventory/tables/sale_group_picture.sql
\i schemas/users/tables/kickstarter.sql
\i schemas/application/tables/resource_group.sql
\i schemas/application/tables/resource_group_resource.sql
\i schemas/application/tables/resource_group_menu.sql
\i schemas/application/tables/menu_group.sql
\i schemas/application/tables/menu_group_menu.sql
\i schemas/transaction/tables/order_postage.sql
\i schemas/transaction/tables/order_postage_customs_content_type.sql
\i schemas/application/tables/news.sql
\i schemas/application/tables/mail_status.sql
\i schemas/application/tables/contact.sql
\i schemas/application/tables/mail.sql
\i schemas/application/tables/mail_recipient.sql
\i schemas/inventory/tables/key.sql
\i schemas/transaction/tables/sale_key.sql


-- TYPES
\i schemas/inventory/types/t_item.sql
\i schemas/inventory/types/t_item_attribute.sql
\i schemas/transaction/types/t_sale_item_ordered.sql
\i schemas/transaction/types/t_order_shipping.sql
\i schemas/transaction/types/t_order_billing.sql
\i schemas/transaction/types/t_digital_item.sql
\i schemas/transaction/types/t_user_digital_item.sql
\i schemas/inventory/types/t_sale_item.sql
\i schemas/inventory/types/t_sale_group.sql
\i schemas/inventory/types/t_sale_group_sale_item.sql
\i schemas/inventory/types/t_sale_item_item.sql
\i schemas/users/types/t_user.sql
\i schemas/transaction/types/t_order.sql
\i schemas/transaction/types/t_address.sql
\i schemas/inventory/types/t_sale_group_picture.sql
\i schemas/users/types/t_kickstarter.sql
\i schemas/users/types/t_user_type.sql
\i schemas/application/types/t_resource_group.sql
\i schemas/users/types/t_user_type_menu.sql
\i schemas/transaction/types/t_order_postage.sql
\i schemas/transaction/types/t_order_postage_customs_content_type.sql
\i schemas/inventory/types/t_item_type.sql
\i schemas/inventory/types/t_item_file_path_orgin.sql
\i schemas/inventory/types/t_item_file_path.sql
\i schemas/application/types/t_news.sql
\i schemas/application/types/t_mail.sql
\i schemas/application/types/t_mail_recipient.sql
\i schemas/application/types/t_mail_status.sql
\i schemas/application/types/t_contact.sql
\i schemas/inventory/types/t_key.sql
\i schemas/transaction/types/t_sale_key.sql

-- VIEWS
\i schemas/inventory/views/v_item.sql
\i schemas/inventory/views/v_item_attribute.sql
\i schemas/transaction/views/v_sale_item_ordered.sql
\i schemas/transaction/views/v_order_shipping.sql
\i schemas/transaction/views/v_digital_item.sql
\i schemas/inventory/views/v_digital_item.sql
\i schemas/transaction/views/v_user_digital_item.sql
\i schemas/inventory/views/v_sale_item.sql
\i schemas/inventory/views/v_sale_group.sql
\i schemas/inventory/views/v_sale_group_sale_item.sql
\i schemas/inventory/views/v_sale_item_item.sql
\i schemas/users/views/v_user.sql
\i schemas/transaction/views/v_address.sql
\i schemas/transaction/views/v_order.sql
\i schemas/inventory/views/v_sale_group_picture.sql
\i schemas/users/views/v_kickstarter.sql
\i schemas/application/views/v_resource_group.sql
\i schemas/users/views/v_user_type_menu.sql
\i schemas/application/views/v_user_type_resource_group.sql
\i schemas/transaction/views/v_order_postage.sql
\i schemas/transaction/views/v_order_postage_customs_content_type.sql
\i schemas/inventory/views/v_item_type.sql
\i schemas/inventory/views/v_item_file_path_orgin.sql
\i schemas/inventory/views/v_item_file_path.sql
\i schemas/application/views/v_news.sql
\i schemas/application/views/v_mail_status.sql
\i schemas/application/views/v_mail.sql
\i schemas/application/views/v_mail_recipient.sql
\i schemas/application/views/v_contact.sql
\i schemas/inventory/views/v_key.sql
\i schemas/transaction/views/v_sale_key.sql
\i schemas/inventory/views/v_get_out_of_stock_sale_item.sql


-- FUNCTIONS
\i schemas/users/functions/authenticate.sql
\i schemas/transaction/functions/get_address.sql
\i schemas/transaction/functions/set_address.sql
\i schemas/transaction/functions/delete_address.sql
\i schemas/inventory/functions/get_item.sql
\i schemas/inventory/functions/set_item.sql
\i schemas/transaction/functions/get_sale_item_ordered.sql
\i schemas/transaction/functions/set_sale_item_ordered.sql
\i schemas/inventory/functions/get_item_attribute.sql
\i schemas/transaction/functions/set_order_shipping.sql
\i schemas/transaction/functions/get_order_shipping.sql
\i schemas/transaction/functions/set_order_billing.sql
\i schemas/transaction/functions/get_order_billing.sql
\i schemas/transaction/functions/get_digital_item.sql
\i schemas/inventory/functions/get_sale_item.sql
\i schemas/inventory/functions/set_sale_item.sql
\i schemas/inventory/functions/get_sale_group.sql
\i schemas/inventory/functions/set_sale_group.sql
\i schemas/inventory/functions/get_sale_group_sale_item.sql
\i schemas/inventory/functions/set_sale_group_sale_item.sql
\i schemas/inventory/functions/delete_sale_group_sale_item.sql
\i schemas/inventory/functions/get_sale_item_item.sql
\i schemas/inventory/functions/set_sale_item_item.sql
\i schemas/inventory/functions/delete_sale_item_item.sql
\i schemas/inventory/functions/do_sale_items_have_physical_items.sql
\i schemas/inventory/functions/get_sale_items_items_total_weight.sql
\i schemas/users/functions/get_user.sql
\i schemas/users/functions/set_user.sql
\i schemas/transaction/functions/get_order.sql
\i schemas/transaction/functions/get_order_by_user_id.sql
\i schemas/transaction/functions/get_order_by_order_number.sql
\i schemas/transaction/functions/get_order_by_order_status_id.sql
\i schemas/transaction/functions/get_order_for_processing.sql
\i schemas/transaction/functions/set_order.sql
\i schemas/transaction/functions/set_order_shipping.sql
\i schemas/transaction/functions/set_order_billing.sql
\i schemas/inventory/functions/do_sale_items_have_digital_items.sql
\i schemas/inventory/functions/get_sale_group_picture.sql
\i schemas/inventory/functions/set_sale_group_picture.sql
\i schemas/users/functions/get_kickstarter.sql
\i schemas/users/functions/set_kickstarter.sql
\i schemas/transaction/functions/delete_ordered_sale_item.sql
\i schemas/transaction/functions/update_kickstarter_order.sql
\i schemas/users/functions/get_user_type.sql
\i schemas/users/functions/set_user_type.sql
\i schemas/application/functions/get_resource_group.sql
\i schemas/application/functions/set_resource_group.sql
\i schemas/users/functions/set_user_type_resource.sql
\i schemas/users/functions/delete_user_type_resource.sql
\i schemas/users/functions/get_user_menu.sql
\i schemas/transaction/functions/get_order_postage.sql
\i schemas/transaction/functions/set_order_postage.sql
\i schemas/transaction/functions/get_order_postage_customs_content_type.sql
\i schemas/transaction/functions/set_order_postage_customs_content_type.sql
\i schemas/inventory/functions/get_item_type.sql
\i schemas/inventory/functions/set_item_type.sql
\i schemas/inventory/functions/get_item_file_path_orgin.sql
\i schemas/inventory/functions/set_item_file_path_orgin.sql
\i schemas/inventory/functions/get_item_file_path.sql
\i schemas/inventory/functions/set_item_file_path.sql
\i schemas/inventory/functions/get_sale_item_available_item.sql
\i schemas/inventory/functions/get_sale_group_available_sale_item.sql
\i schemas/inventory/functions/delete_sale_group_picture.sql
\i schemas/application/functions/get_news.sql
\i schemas/application/functions/set_news.sql
\i schemas/application/functions/delete_news.sql
\i schemas/application/functions/get_mail.sql
\i schemas/application/functions/set_mail.sql
\i schemas/application/functions/delete_mail.sql
\i schemas/application/functions/get_mail_recipient.sql
\i schemas/application/functions/set_mail_recipient.sql
\i schemas/application/functions/delete_mail_recipient.sql
\i schemas/application/functions/get_mail_status.sql
\i schemas/application/functions/get_contact.sql
\i schemas/application/functions/get_contact_by_user_id.sql
\i schemas/application/functions/set_contact.sql
\i schemas/application/functions/get_available_contact.sql
\i schemas/inventory/functions/get_key.sql
\i schemas/inventory/functions/get_available_key.sql
\i schemas/inventory/functions/set_key.sql
\i schemas/inventory/functions/delete_key.sql
\i schemas/transaction/functions/get_sale_key.sql
\i schemas/transaction/functions/set_sale_key.sql
\i schemas/transaction/functions/get_user_digital_item.sql
\i schemas/inventory/functions/update_item_quantity.sql
\i schemas/inventory/functions/get_out_of_stock_sale_item.sql
\i schemas/users/functions/is_user_type_in_use.sql
\i schemas/users/functions/delete_user_type.sql
\i schemas/transaction/functions/fix_address.sql

-- INDEXES
\i schemas/transaction/indexes/i_sale_item_ordered_sale_item_id.sql

--ROLLBACK;
COMMIT;